{"name": "Принятие заказа с неверным ID курьера", "status": "passed", "start": 1727816008104, "stop": 1727816008615, "uuid": "3ec0358c-3c94-4291-9bf2-cee5a52dd08a", "historyId": "7340bb1811a392153b914aaffb7f586b", "testCaseId": "7340bb1811a392153b914aaffb7f586b", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_invalid_courier_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "POPOV"}, {"name": "thread", "value": "21720-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}