{"name": "Принятие заказа с неверным ID курьера", "status": "passed", "start": 1727815812615, "stop": 1727815813330, "uuid": "21428709-b4d9-4e95-8a06-c7a87d1efb88", "historyId": "7340bb1811a392153b914aaffb7f586b", "testCaseId": "7340bb1811a392153b914aaffb7f586b", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_invalid_courier_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "POPOV"}, {"name": "thread", "value": "30656-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}