{"name": "Принятие заказа с неверным ID заказа", "status": "passed", "start": 1727816011279, "stop": 1727816011892, "uuid": "26cf8def-56b9-4cf9-a4bd-b95c7bb95784", "historyId": "e4f726252d51a7f0f084ca15b11fa1cc", "testCaseId": "e4f726252d51a7f0f084ca15b11fa1cc", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_invalid_order_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "POPOV"}, {"name": "thread", "value": "21720-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}