{"name": "Принятие заказа с неверным ID курьера", "status": "passed", "start": 1727815751071, "stop": 1727815751603, "uuid": "097827aa-7d00-48f9-93c7-e91d0063ff43", "historyId": "7340bb1811a392153b914aaffb7f586b", "testCaseId": "7340bb1811a392153b914aaffb7f586b", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_invalid_courier_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "POPOV"}, {"name": "thread", "value": "13800-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}